# Phase 0 - Week 2 - Day 1 PM - Pandas for Data Analysis

## A. Setup

In [1]:
# Import library

import pandas as pd

## B. Create a DataFrame and a Series

### B.1 - DataFrame

**A DataFrame is a 2-dimensional tabular data structure in Pandas.** You can create one from various sources, including dictionaries, lists, or external files like `CSV`.

In [2]:
# Creating a DataFrame from a dictionary

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 22],
    'City': ['New York', 'London', 'Paris']}

df = pd.DataFrame(data)

print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris

### B.2 - Series

**A Series is a one-dimensional labeled array in Pandas.** You can create one from a list, dictionary, or an ndarray.

In [3]:
# Creating a Series from a list

data = [10, 20, 30, 40, 50]

series = pd.Series(data)

print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

## C. Data Loading

To load data into a Pandas DataFrame from a source, you can use various methods depending on the data source.

### C.1 - From a `CSV` file

#### C.1.1 - A local file

Since we now work on Google Colab, and it's not convinient to upload the file every we connect the runtime, we will "download" the data from sources into our Google Colab storage using `wget` prompt command.

In [4]:
# Download a CSV file into local computer

!wget https://raw.githubusercontent.com/FTDS-learning-materials/phase-0/refs/heads/v2.4/src/teams.csv

--2026-01-08 12:26:10--  https://raw.githubusercontent.com/FTDS-learning-materials/phase-0/refs/heads/v2.4/src/teams.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24958 (24K) [text/plain]
Saving to: ‘teams.csv.1’

teams.csv.1         100%[===================>]  24.37K  --.-KB/s    in 0.001s

2026-01-08 12:26:10 (37.6 MB/s) - ‘teams.csv.1’ saved [24958/24958]

Use `pd.read_csv` to open the file.

In [5]:
# Open a CSV file using Pandas

teams = pd.read_csv('teams.csv')
teams

,division,conference,school_name,roster_url,id
0,FBS (Division I-A Teams),American Athletic,Cincinnati,http://espn.go.com/ncf/teams/roster?teamId=2132,1
1,FBS (Division I-A Teams),American Athletic,Connecticut,http://espn.go.com/ncf/teams/roster?teamId=41,2
2,FBS (Division I-A Teams),American Athletic,Houston,http://espn.go.com/ncf/teams/roster?teamId=248,3
3,FBS (Division I-A Teams),American Athletic,Louisville,http://espn.go.com/ncf/teams/roster?teamId=97,4
4,FBS (Division I-A Teams),American Athletic,Memphis,http://espn.go.com/ncf/teams/roster?teamId=235,5
...,...,...,...,...,...
247,FCS (Division I-AA Teams),SWAC,Jackson State,http://espn.go.com/ncf/teams/roster?teamId=2296,248
248,FCS (Division I-AA Teams),SWAC,Mississippi Valley State,http://espn.go.com/ncf/teams/roster?teamId=2400,249
249,FCS (Division I-AA Teams),SWAC,Prairie View A&M,http://espn.go.com/ncf/teams/roster?teamId=2504,250
250,FCS (Division I-AA Teams),SWAC,Southern University,http://espn.go.com/ncf/teams/roster?teamId=2582,251
251,FCS (Division I-AA Teams),SWAC,Texas Southern,http://espn.go.com/ncf/teams/roster?teamId=2640,252

#### C.1.2 - From a URL

You can specify a URL that download a data directly after we click on it to the Pandas data loader.

In [6]:
# Open a URL using Pandas

house = pd.read_csv('https://raw.githubusercontent.com/FTDS-learning-materials/phase-0/refs/heads/v2.4/src/kc_house_data.csv')
house

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

### C.2 - From a `TSV` file  or other format file

`pd.read_csv` can also read any other extensions such as `.tsv`, `.txt`, but only if you specify the delimiter of the data.

The delimiter of `CSV` file is comma. Instead, the `TSV` file is tab or `\t`.

In [8]:
# Open a TSV file using Pandas

tsv_df = pd.read_csv('https://raw.githubusercontent.com/FTDS-learning-materials/phase-0/refs/heads/v2.4/src/cities_world.tsv', delimiter='\t')
tsv_df

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
0,Tokyo/Yokohama,35.6895,139.6917,Japan,33200000,6993,4750,1
1,New York Metro,40.7128,-74.0059,USA,17800000,8683,2050,2
2,Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3
3,Seoul/Incheon,37.5665,126.9780,South Korea,17500000,1049,16700,4
4,Mexico City,23.6345,-102.5528,Mexico,17400000,2072,8400,5
...,...,...,...,...,...,...,...,...
120,Copenhagen,55.6761,12.5683,Denmark,1525000,816,1850,121
121,Brisbane,-27.4698,153.0251,Australia,1508000,1603,950,122
122,Riverside/San Bernardino,33.9533,-117.3962,USA,1507000,1136,1350,123
123,Cincinnati,39.1031,-84.5120,USA,1503000,1740,850,124
124,Accra,5.6037,-0.1870,Ghana,1500000,453,3300,125

How about if we change the delimiter to default (',')?

In [9]:
# Try open a TSV file using default delimiter

tsv_df2 = pd.read_csv('https://raw.githubusercontent.com/FTDS-learning-materials/phase-0/refs/heads/v2.4/src/cities_world.tsv')
tsv_df2

    City\tLatitude\tLongitude\tCountry\tPopulation\tLand_area\tDensity\tNumber
0    Tokyo/Yokohama\t35.6895\t139.6917\tJapan\t3320...
1    New York Metro\t40.7128\t-74.0059\tUSA\t178000...
2    Sao Paulo\t-23.5505\t-46.6333\tBrazil\t1770000...
3    Seoul/Incheon\t37.5665\t126.978\tSouth Korea\t...
4    Mexico City\t23.6345\t-102.5528\tMexico\t17400...
..                                                 ...
120  Copenhagen\t55.6761\t12.5683\tDenmark\t1525000...
121  Brisbane\t-27.4698\t153.0251\tAustralia\t15080...
122  Riverside/San Bernardino\t33.9533\t-117.3962\t...
123  Cincinnati\t39.1031\t-84.5120\tUSA\t1503000\t1...
124  Accra\t5.6037\t-0.1870\tGhana\t1500000\t453\t3...

[125 rows x 1 columns]

As you can see, the values ​​in each column cannot be separated.

### C.3 - From an Excel file

Excel file is special that has different encode, format to csv or other text files. Therefore, Pandas provides a particular function that is `pd.read_excel()`.

In [12]:
# Open an Excel file using Pandas

excel_file = 'https://github.com/FTDS-learning-materials/phase-0/raw/refs/heads/v2.4/src/data_penjualan.xlsx'

sales_df = pd.read_excel(excel_file)
sales_df

        Bulan  Penjualan
0     Januari       1000
1    Februari        200
2       Maret       5000
3       April        654
4         Mei       1200
5        Juni        760
6        Juli       1000
7     Agustus       1100
8   September       1200
9     Oktober       1500
10   November       4000
11   Desember       7600

Remember that excel file can possess more than one sheet. So, how to check sheets in the excel file?

In [13]:
# List all sheets from an Excel file

pd.ExcelFile(excel_file).sheet_names

['2020', '2021']

To open specific sheet, you can add `sheet_name` argument when use `pd.read_excel`. Note that by default, `pd.read_excel` will open the first sheet.

In [14]:
# Open a specific sheet from an Excel file

sales_df_2021 = pd.read_excel(excel_file, sheet_name='2021')
sales_df_2021

        Bulan  Penjualan
0     Januari       1200
1    Februari       1500
2       Maret       4000
3       April       7600
4         Mei       1200
5        Juni        760
6        Juli       1000
7     Agustus       1100
8   September       1300
9     Oktober       1000
10   November       1100
11   Desember       1200

## D. Data Exploration

We will use `cities world` data. However, we will load again.

In [15]:
# Data loading

df = pd.read_csv('https://raw.githubusercontent.com/FTDS-learning-materials/phase-0/refs/heads/v2.4/src/cities_world.tsv', delimiter='\t')

### D.1 - Show first 5 data and last 5 data

In [16]:
# Show first 5 data

df.head()

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
0,Tokyo/Yokohama,35.6895,139.6917,Japan,33200000,6993,4750,1
1,New York Metro,40.7128,-74.0059,USA,17800000,8683,2050,2
2,Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3
3,Seoul/Incheon,37.5665,126.9780,South Korea,17500000,1049,16700,4
4,Mexico City,23.6345,-102.5528,Mexico,17400000,2072,8400,5

In [17]:
# Show last 5 data

df.tail()

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
120,Copenhagen,55.6761,12.5683,Denmark,1525000,816,1850,121
121,Brisbane,-27.4698,153.0251,Australia,1508000,1603,950,122
122,Riverside/San Bernardino,33.9533,-117.3962,USA,1507000,1136,1350,123
123,Cincinnati,39.1031,-84.5120,USA,1503000,1740,850,124
124,Accra,5.6037,-0.1870,Ghana,1500000,453,3300,125

### D.2 - Show number of rows and columns in a DataFrame

Thw output will be a Tuple -> `(n_rows,n_cols)`

In [18]:
# Check number of rows and columns

df.shape

(125, 8)

### D.3 - Show DataFrame summary

In [19]:
# Check summary DataFrame

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        125 non-null    object
 1   Latitude    125 non-null    float64
 2   Longitude   125 non-null    float64
 3   Country     125 non-null    object
 4   Population  125 non-null    int64
 5   Land_area   125 non-null    int64
 6   Density     125 non-null    int64
 7   Number      125 non-null    int64
dtypes: float64(2), int64(4), object(2)
memory usage: 7.9+ KB

### D.4 - Show descriptive statistics of the numerical columns

In [20]:
# Show descriptive statistics

df.describe()

,Latitude,Longitude,Population,Land_area,Density,Number
count,125.000000,125.000000,1.250000e+02,125.000000,125.000000,125.000000
mean,25.005552,5.567330,5.283232e+06,1399.624000,5403.600000,63.000000
std,25.394396,80.124674,4.855835e+06,1340.851906,4935.181371,36.228442
min,-37.813600,-123.120700,1.500000e+06,376.000000,700.000000,1.000000
25%,14.599500,-74.005900,2.100000e+06,583.000000,2250.000000,32.000000
50%,33.749000,12.496400,3.502000e+06,816.000000,3800.000000,63.000000
75%,41.805700,67.009900,6.000000e+06,1740.000000,7700.000000,94.000000
max,59.934300,153.025100,3.320000e+07,8683.000000,29650.000000,125.000000

### D.5 - Show column names

In [21]:
# Show all column names

df.columns

Index(['City', 'Latitude', 'Longitude', 'Country', 'Population', 'Land_area',
       'Density', 'Number'],
      dtype='object')

### D.6 - Show index list

In [22]:
# Show index list

df.index

RangeIndex(start=0, stop=125, step=1)

### D.7 - Show data types from each column

In [23]:
# Show all data types

df.dtypes

City           object
Latitude      float64
Longitude     float64
Country        object
Population      int64
Land_area       int64
Density         int64
Number          int64
dtype: object

### D.8 - Show number of unique values from each column

In [24]:
# Show number of unique values from each column

df.nunique()

City          125
Latitude      125
Longitude     125
Country        52
Population    109
Land_area      90
Density        96
Number        125
dtype: int64

### D.9 - Show unique values and its frequency from a specific column

In [25]:
# Show unique values and its frequency from column `Country`

df['Country'].value_counts()

Country
USA             26
Brazil           9
China            6
India            6
Germany          6
Japan            5
South Africa     4
UK               3
Italy            3
Canada           3
Saudi Arabia     3
Mexico           3
Australia        3
Taiwan           2
Spain            2
Poland           2
Russia           2
Pakistan         2
Turkey           2
South Korea      1
Colombia         1
Iran             1
France           1
Philippines      1
Indonesia        1
Nigeria          1
Egypt            1
Argentina        1
Vietnam          1
Congo            1
Chile            1
Iraq             1
Malaysia         1
Sudan            1
Thailand         1
Peru             1
Greece           1
Singapore        1
Portugal         1
Israel           1
Puerto Rico      1
Uzbekistan       1
Azerbaijan       1
UAE              1
Lebanon          1
Hungary          1
Zimbabwe         1
Kuwait           1
Belgium          1
Austria          1
Denmark          1
Ghana            1
Name: count, dtype: int64

### D.10 - Show all unique values from a specific column

In [26]:
# SHow all unique values from column `City`

df['City'].unique()

array(['Tokyo/Yokohama', 'New York Metro', 'Sao Paulo', 'Seoul/Incheon',
       'Mexico City', 'Osaka/Kobe/Kyoto', 'Manila', 'Mumbai', 'Delhi',
       'Jakarta', 'Lagos', 'Kolkata', 'Cairo', 'Los Angeles',
       'Buenos Aires', 'Rio de Janeiro', 'Moscow', 'Shanghai', 'Karachi',
       'Paris', 'Istanbul', 'Nagoya', 'Beijing', 'Chicago', 'London',
       'Shenzhen', 'Essen/DГјsseldorf', 'Tehran', 'Bogota', 'Lima',
       'Bangkok', 'Johannesburg/East Rand', 'Chennai', 'Taipei',
       'Baghdad', 'Santiago', 'Bangalore', 'Hyderabad', 'St Petersburg',
       'Philadelphia', 'Lahore', 'Kinshasa', 'Miami', 'Ho Chi Minh City',
       'Madrid', 'Tianjin', 'Kuala Lumpur', 'Toronto', 'Milan',
       'Shenyang', 'Dallas/Fort Worth', 'Boston', 'Belo Horizonte',
       'Khartoum', 'Riyadh', 'Singapore', 'Washington', 'Detroit',
       'Barcelona', 'Houston', 'Athens', 'Berlin', 'Sydney', 'Atlanta',
       'Guadalajara', 'San Francisco/Oakland', 'Montreal', 'Monterey',
       'Melbourne', 'Ankara', 'Recife', 'Phoenix/Mesa', 'Durban',
       'Porto Alegre', 'Dalian', 'Jeddah', 'Seattle', 'Cape Town',
       'San Diego', 'Fortaleza', 'Curitiba', 'Rome', 'Naples',
       'Minneapolis/St. Paul', 'Tel Aviv', 'Birmingham', 'Frankfurt',
       'Lisbon', 'Manchester', 'San Juan', 'Katowice', 'Tashkent',
       'Fukuoka', 'Baku/Sumqayit', 'St. Louis', 'Baltimore', 'Sapporo',
       'Tampa/St. Petersburg', 'Taichung', 'Warsaw', 'Denver',
       'Cologne/Bonn', 'Hamburg', 'Dubai', 'Pretoria', 'Vancouver',
       'Beirut', 'Budapest', 'Cleveland', 'Pittsburgh', 'Campinas',
       'Harare', 'Brasilia', 'Kuwait', 'Munich', 'Portland', 'Brussels',
       'Vienna', 'San Jose', 'Dammam', 'Copenhagen', 'Brisbane',
       'Riverside/San Bernardino', 'Cincinnati', 'Accra'], dtype=object)

# E. Data Manipulation

## Sorting Data

In [ ]:
df.sort_values(by='City',ascending=True) #ascending

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
124,Accra,5.6037,-0.1870,Ghana,1500000,453,3300,125
69,Ankara,39.9334,32.8597,Turkey,3100000,583,5300,70
60,Athens,37.9838,23.7275,Greece,3685000,684,5400,61
63,Atlanta,33.7490,-84.3880,USA,3500000,5083,700,64
34,Baghdad,33.3128,44.3615,Iraq,5500000,596,9250,35
...,...,...,...,...,...,...,...,...
47,Toronto,43.6532,-79.3832,Canada,4367000,1655,2650,48
105,Vancouver,49.2827,-123.1207,Canada,1830000,1120,1650,106
117,Vienna,48.2082,16.3738,Austria,1550000,453,3400,118
99,Warsaw,52.2297,21.0122,Poland,2000000,466,4300,100
56,Washington,47.7511,-120.7401,USA,3934000,2996,1300,57

In [ ]:
df.sort_values(by='City',ascending=False) #descending

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
56,Washington,47.7511,-120.7401,USA,3934000,2996,1300,57
99,Warsaw,52.2297,21.0122,Poland,2000000,466,4300,100
117,Vienna,48.2082,16.3738,Austria,1550000,453,3400,118
105,Vancouver,49.2827,-123.1207,Canada,1830000,1120,1650,106
47,Toronto,43.6532,-79.3832,Canada,4367000,1655,2650,48
...,...,...,...,...,...,...,...,...
34,Baghdad,33.3128,44.3615,Iraq,5500000,596,9250,35
63,Atlanta,33.7490,-84.3880,USA,3500000,5083,700,64
60,Athens,37.9838,23.7275,Greece,3685000,684,5400,61
69,Ankara,39.9334,32.8597,Turkey,3100000,583,5300,70
124,Accra,5.6037,-0.1870,Ghana,1500000,453,3300,125

## Slicing - Accessing Rows and Columns

### Accessing Columns

In [ ]:
df['City'] #single column

0                Tokyo/Yokohama
1                New York Metro
2                     Sao Paulo
3                 Seoul/Incheon
4                   Mexico City
                 ...
120                  Copenhagen
121                    Brisbane
122    Riverside/San Bernardino
123                  Cincinnati
124                       Accra
Name: City, Length: 125, dtype: object

In [ ]:
df[['Longitude','Latitude']] #multiple columns

     Longitude  Latitude
0     139.6917   35.6895
1     -74.0059   40.7128
2     -46.6333  -23.5505
3     126.9780   37.5665
4    -102.5528   23.6345
..         ...       ...
120    12.5683   55.6761
121   153.0251  -27.4698
122  -117.3962   33.9533
123   -84.5120   39.1031
124    -0.1870    5.6037

[125 rows x 2 columns]

In [ ]:
# If the column names are valid Python identifiers
# do not conflict with DataFrame attributes,
# and the column name follows the variable name rules,
# you can use dot notation to access columns.

df.Land_area

0      6993
1      8683
2      1968
3      1049
4      2072
       ...
120     816
121    1603
122    1136
123    1740
124     453
Name: Land_area, Length: 125, dtype: int64

### Accessing Rows

#### Using .loc

In [ ]:
df_new = df.set_index('City')
df_new.head()

,Latitude,Longitude,Country,Population,Land_area,Density,Number
City,,,,,,,
Tokyo/Yokohama,35.6895,139.6917,Japan,33200000,6993,4750,1
New York Metro,40.7128,-74.0059,USA,17800000,8683,2050,2
Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3
Seoul/Incheon,37.5665,126.9780,South Korea,17500000,1049,16700,4
Mexico City,23.6345,-102.5528,Mexico,17400000,2072,8400,5

In [ ]:
df_new.loc['Tokyo/Yokohama']

Latitude       35.6895
Longitude     139.6917
Country          Japan
Population    33200000
Land_area         6993
Density           4750
Number               1
Name: Tokyo/Yokohama, dtype: object

In [ ]:
df_new['New York Metro':'Mexico City']

,Latitude,Longitude,Country,Population,Land_area,Density,Number
City,,,,,,,
New York Metro,40.7128,-74.0059,USA,17800000,8683,2050,2
Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3
Seoul/Incheon,37.5665,126.9780,South Korea,17500000,1049,16700,4
Mexico City,23.6345,-102.5528,Mexico,17400000,2072,8400,5

In [ ]:
df_new.loc[0]

KeyError: 0

#### Using .iloc

In [ ]:
df_new.iloc['Tokyo/Yokohama']

TypeError: Cannot index by location index with a non-integer key

In [ ]:
df_new.iloc[0]

Latitude       35.6895
Longitude     139.6917
Country          Japan
Population    33200000
Land_area         6993
Density           4750
Number               1
Name: Tokyo/Yokohama, dtype: object

In [ ]:
df_new.iloc[5:9] #-> only takes row-5 to row-8

,Latitude,Longitude,Country,Population,Land_area,Density,Number
City,,,,,,,
Osaka/Kobe/Kyoto,34.6937,135.5022,Japan,16425000,2564,6400,6
Manila,14.5995,120.9842,Philippines,14750000,1399,10550,7
Mumbai,19.0760,72.8777,India,14350000,484,29650,8
Delhi,28.7041,77.1025,India,14300000,1295,11050,9

## Query/Filtering

### Boolean Indexing

#### Single Condition

Retrieve data that has population more than 15 million people

In [ ]:
df[df['Population']>15000000]

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
0,Tokyo/Yokohama,35.6895,139.6917,Japan,33200000,6993,4750,1
1,New York Metro,40.7128,-74.0059,USA,17800000,8683,2050,2
2,Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3
3,Seoul/Incheon,37.5665,126.9780,South Korea,17500000,1049,16700,4
4,Mexico City,23.6345,-102.5528,Mexico,17400000,2072,8400,5
5,Osaka/Kobe/Kyoto,34.6937,135.5022,Japan,16425000,2564,6400,6

#### Multiple Conditions

Cities that has more than 10 million of population in Southern Hemisphere

In [ ]:
df[(df['Population']>10000000) & (df['Latitude']<0)]

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
2,Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3
9,Jakarta,-6.1745,106.8227,Indonesia,14250000,1360,10500,10
14,Buenos Aires,-34.6037,-58.3816,Argentina,11200000,2266,4950,15
15,Rio de Janeiro,-22.9068,-43.1729,Brazil,10800000,1580,6850,16

### Query Method

In [ ]:
df.query('Population > 15000000')

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
0,Tokyo/Yokohama,35.6895,139.6917,Japan,33200000,6993,4750,1
1,New York Metro,40.7128,-74.0059,USA,17800000,8683,2050,2
2,Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3
3,Seoul/Incheon,37.5665,126.9780,South Korea,17500000,1049,16700,4
4,Mexico City,23.6345,-102.5528,Mexico,17400000,2072,8400,5
5,Osaka/Kobe/Kyoto,34.6937,135.5022,Japan,16425000,2564,6400,6

In [ ]:
df.query('Population > 10000000 and Latitude < 0')

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
2,Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3
9,Jakarta,-6.1745,106.8227,Indonesia,14250000,1360,10500,10
14,Buenos Aires,-34.6037,-58.3816,Argentina,11200000,2266,4950,15
15,Rio de Janeiro,-22.9068,-43.1729,Brazil,10800000,1580,6850,16

### isin Method

Retrieve list City only in Argentina, Brazil, and Chile:

In [ ]:
df[df['Country'].isin(['Argentina','Brazil','Chile'])]

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
2,Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3
14,Buenos Aires,-34.6037,-58.3816,Argentina,11200000,2266,4950,15
15,Rio de Janeiro,-22.9068,-43.1729,Brazil,10800000,1580,6850,16
35,Santiago,-33.4489,-70.6693,Chile,5425000,648,8400,36
52,Belo Horizonte,-19.9245,-43.9352,Brazil,4000000,868,4600,53
70,Recife,-8.0476,-34.8770,Brazil,3025000,376,8050,71
73,Porto Alegre,-30.0347,-51.2177,Brazil,2800000,583,4800,74
79,Fortaleza,-3.7319,-38.5267,Brazil,2650000,583,4550,80
80,Curitiba,-25.4244,-49.2654,Brazil,2500000,648,3850,81
110,Campinas,-22.9099,-47.0626,Brazil,1750000,492,3550,111
112,Brasilia,-15.7942,-47.8822,Brazil,1625000,583,2800,113

### str Method

Retrieve Cities that contains 'City' on their name:

In [ ]:
df[df['City'].str.contains('City')]

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
4,Mexico City,23.6345,-102.5528,Mexico,17400000,2072,8400,5
43,Ho Chi Minh City,10.8231,106.6297,Vietnam,4900000,518,9450,44

### .loc Method

In [ ]:
df.loc[(df['Population']>10000000)]

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
0,Tokyo/Yokohama,35.6895,139.6917,Japan,33200000,6993,4750,1
1,New York Metro,40.7128,-74.0059,USA,17800000,8683,2050,2
2,Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3
3,Seoul/Incheon,37.5665,126.9780,South Korea,17500000,1049,16700,4
4,Mexico City,23.6345,-102.5528,Mexico,17400000,2072,8400,5
5,Osaka/Kobe/Kyoto,34.6937,135.5022,Japan,16425000,2564,6400,6
6,Manila,14.5995,120.9842,Philippines,14750000,1399,10550,7
7,Mumbai,19.0760,72.8777,India,14350000,484,29650,8
8,Delhi,28.7041,77.1025,India,14300000,1295,11050,9
9,Jakarta,-6.1745,106.8227,Indonesia,14250000,1360,10500,10
10,Lagos,6.5244,3.3792,Nigeria,13400000,738,18150,11
11,Kolkata,22.5726,88.3639,India,12700000,531,23900,12
12,Cairo,30.0444,31.2357,Egypt,12200000,1295,9400,13
13,Los Angeles,34.0522,-118.2437,USA,11789000,4320,2750,14
14,Buenos Aires,-34.6037,-58.3816,Argentina,11200000,2266,4950,15
15,Rio de Janeiro,-22.9068,-43.1729,Brazil,10800000,1580,6850,16
16,Moscow,55.7558,37.6173,Russia,10500000,2150,4900,17

## Add Column and Row

### Add a New Column

In [ ]:
df['New_Pop'] = df['Land_area'] * df['Density']
df.head()

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number,New_Pop
0,Tokyo/Yokohama,35.6895,139.6917,Japan,33200000,6993,4750,1,33216750
1,New York Metro,40.7128,-74.0059,USA,17800000,8683,2050,2,17800150
2,Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3,17712000
3,Seoul/Incheon,37.5665,126.9780,South Korea,17500000,1049,16700,4,17518300
4,Mexico City,23.6345,-102.5528,Mexico,17400000,2072,8400,5,17404800

### Add a New Row

1. First Method : Using `.loc`

In [ ]:
# new row infomation
data = {
    'City': 'Surabaya',
    'Latitude': -7.2575,
    'Longitude': 112.7521,
    'Country': 'Indonesia',
    'Population': 2949585,
    'Land_area': 351,
    'Density': 8406,
    'Number':126
}

# use len() to put the new data at the last row
df.loc[len(df)] = data
df.tail()

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number,New_Pop
121,Brisbane,-27.4698,153.0251,Australia,1508000,1603,950,122,1522850.0
122,Riverside/San Bernardino,33.9533,-117.3962,USA,1507000,1136,1350,123,1533600.0
123,Cincinnati,39.1031,-84.5120,USA,1503000,1740,850,124,1479000.0
124,Accra,5.6037,-0.1870,Ghana,1500000,453,3300,125,1494900.0
125,Surabaya,-7.2575,112.7521,Indonesia,2949585,351,8406,126,NaN

2. Method 2: Using `concat()`

In [ ]:
# new row infomation
data = {
    'City': 'Bandung',
    'Latitude': -6.9147,
    'Longitude': 107.6098,
    'Country': 'Indonesia',
    'Population': 2498657,
    'Land_area': 167,
    'Density': 14907,
    'Number':210
}

# create a dataframe as a new row
new_row = pd.DataFrame([data])

# concatenate the new row with the original dataframe
df = pd.concat([df, new_row], ignore_index=True)
df.tail()

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number,New_Pop
122,Riverside/San Bernardino,33.9533,-117.3962,USA,1507000,1136,1350,123,1533600.0
123,Cincinnati,39.1031,-84.5120,USA,1503000,1740,850,124,1479000.0
124,Accra,5.6037,-0.1870,Ghana,1500000,453,3300,125,1494900.0
125,Surabaya,-7.2575,112.7521,Indonesia,2949585,351,8406,126,NaN
126,Bandung,-6.9147,107.6098,Indonesia,2498657,167,14907,210,NaN

## Remove Columns and Rows

### Remove Columns

In [ ]:
df.drop(columns='New_Pop') #or df.drop('New_Pop', axis = 1)
# you can add inplace=True argument into the function to overwrite the old variable

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
0,Tokyo/Yokohama,35.6895,139.6917,Japan,33200000,6993,4750,1
1,New York Metro,40.7128,-74.0059,USA,17800000,8683,2050,2
2,Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3
3,Seoul/Incheon,37.5665,126.9780,South Korea,17500000,1049,16700,4
4,Mexico City,23.6345,-102.5528,Mexico,17400000,2072,8400,5
...,...,...,...,...,...,...,...,...
122,Riverside/San Bernardino,33.9533,-117.3962,USA,1507000,1136,1350,123
123,Cincinnati,39.1031,-84.5120,USA,1503000,1740,850,124
124,Accra,5.6037,-0.1870,Ghana,1500000,453,3300,125
125,Surabaya,-7.2575,112.7521,Indonesia,2949585,351,8406,126
126,Bandung,-6.9147,107.6098,Indonesia,2498657,167,14907,210

In [ ]:
#We don't add inplace=True or don't running a syntax like this: df = df.drop(columns='New_Pop')
#So, if we call the dataframe, 'Num_Pop' still there

df.head()

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number,New_Pop
0,Tokyo/Yokohama,35.6895,139.6917,Japan,33200000,6993,4750,1,33216750.0
1,New York Metro,40.7128,-74.0059,USA,17800000,8683,2050,2,17800150.0
2,Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3,17712000.0
3,Seoul/Incheon,37.5665,126.9780,South Korea,17500000,1049,16700,4,17518300.0
4,Mexico City,23.6345,-102.5528,Mexico,17400000,2072,8400,5,17404800.0

In [ ]:
# But not if we use 'del' keyword, it changes the variable automatically and directly
# without assign a new variable or inplace argument
del df['New_Pop']

In [ ]:
df.head()

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
0,Tokyo/Yokohama,35.6895,139.6917,Japan,33200000,6993,4750,1
1,New York Metro,40.7128,-74.0059,USA,17800000,8683,2050,2
2,Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3
3,Seoul/Incheon,37.5665,126.9780,South Korea,17500000,1049,16700,4
4,Mexico City,23.6345,-102.5528,Mexico,17400000,2072,8400,5

### Remove Rows

### Boolean Indexing

In [ ]:
df[~(df['City']=='Surabaya')]

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
0,Tokyo/Yokohama,35.6895,139.6917,Japan,33200000,6993,4750,1
1,New York Metro,40.7128,-74.0059,USA,17800000,8683,2050,2
2,Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3
3,Seoul/Incheon,37.5665,126.9780,South Korea,17500000,1049,16700,4
4,Mexico City,23.6345,-102.5528,Mexico,17400000,2072,8400,5
...,...,...,...,...,...,...,...,...
121,Brisbane,-27.4698,153.0251,Australia,1508000,1603,950,122
122,Riverside/San Bernardino,33.9533,-117.3962,USA,1507000,1136,1350,123
123,Cincinnati,39.1031,-84.5120,USA,1503000,1740,850,124
124,Accra,5.6037,-0.1870,Ghana,1500000,453,3300,125
126,Bandung,-6.9147,107.6098,Indonesia,2498657,167,14907,210

### Using drop()

In [ ]:
df.drop(index=[125, 126])    # you could just set index=125 if only want to drop 125

,City,Latitude,Longitude,Country,Population,Land_area,Density,Number
0,Tokyo/Yokohama,35.6895,139.6917,Japan,33200000,6993,4750,1
1,New York Metro,40.7128,-74.0059,USA,17800000,8683,2050,2
2,Sao Paulo,-23.5505,-46.6333,Brazil,17700000,1968,9000,3
3,Seoul/Incheon,37.5665,126.9780,South Korea,17500000,1049,16700,4
4,Mexico City,23.6345,-102.5528,Mexico,17400000,2072,8400,5
...,...,...,...,...,...,...,...,...
120,Copenhagen,55.6761,12.5683,Denmark,1525000,816,1850,121
121,Brisbane,-27.4698,153.0251,Australia,1508000,1603,950,122
122,Riverside/San Bernardino,33.9533,-117.3962,USA,1507000,1136,1350,123
123,Cincinnati,39.1031,-84.5120,USA,1503000,1740,850,124
124,Accra,5.6037,-0.1870,Ghana,1500000,453,3300,125

## F. Data Grouping

### F.1 - Grouping Based On A Single Column

In [ ]:
# One aggregation function
df.groupby('Country').mean(numeric_only=True)  # Automatically uses numeric columns

,Latitude,Longitude,Population,Land_area,Density,Number
Country,,,,,,
Argentina,-34.603700,-58.381600,1.120000e+07,2266.000000,4950.000000,15.000000
Australia,-33.050733,149.732500,2.724000e+06,1790.000000,1516.666667,84.666667
Austria,48.208200,16.373800,1.550000e+06,453.000000,3400.000000,118.000000
Azerbaijan,40.409300,49.867100,2.100000e+06,544.000000,3850.000000,94.000000
Belgium,50.850300,4.351700,1.570000e+06,712.000000,2200.000000,117.000000
Brazil,-19.147167,-44.730333,5.205556e+06,853.444444,5338.888889,66.888889
Canada,46.145867,-92.023733,3.137667e+06,1505.000000,2050.000000,73.666667
Chile,-33.448900,-70.669300,5.425000e+06,648.000000,8400.000000,36.000000
China,35.580267,119.031033,6.385667e+06,542.500000,11483.333333,39.666667
Colombia,4.711000,-74.072100,7.000000e+06,518.000000,13500.000000,29.000000
Congo,-4.387100,15.970000,5.000000e+06,469.000000,10650.000000,42.000000
Denmark,55.676100,12.568300,1.525000e+06,816.000000,1850.000000,121.000000
Egypt,30.044400,31.235700,1.220000e+07,1295.000000,9400.000000,13.000000
France,48.856600,2.352200,9.645000e+06,2723.000000,3550.000000,20.000000
Germany,51.118367,9.605783,3.128333e+06,1128.833333,2775.000000,82.666667
Ghana,5.603700,-0.187000,1.500000e+06,453.000000,3300.000000,125.000000
Greece,37.983800,23.727500,3.685000e+06,684.000000,5400.000000,61.000000
Hungary,47.497900,19.040200,1.800000e+06,702.000000,2550.000000,108.000000
India,18.965333,79.116017,9.666667e+06,640.166667,16358.333333,22.833333
Indonesia,-6.782233,109.061533,6.566081e+06,626.000000,11271.000000,115.333333
Iran,35.689200,51.389000,7.250000e+06,686.000000,10550.000000,28.000000
Iraq,33.312800,44.361500,5.500000e+06,596.000000,9250.000000,35.000000
Israel,32.085300,34.781800,2.300000e+06,453.000000,5050.000000,85.000000
Italy,42.740000,11.983467,3.050000e+06,993.000000,3266.666667,71.333333
Japan,36.443420,136.771280,1.257000e+07,2678.000000,4650.000000,43.800000
Kuwait,29.311700,47.481800,1.600000e+06,544.000000,2950.000000,114.000000
Lebanon,33.893800,35.501800,1.800000e+06,648.000000,2800.000000,107.000000
Malaysia,3.139000,101.686900,4.400000e+06,1606.000000,2750.000000,47.000000
Mexico,23.326933,-102.072833,8.033333e+06,1049.000000,7000.000000,46.000000
Nigeria,6.524400,3.379200,1.340000e+07,738.000000,18150.000000,11.000000
Pakistan,28.208050,70.683550,7.450000e+06,570.000000,13550.000000,30.000000
Peru,-12.046374,-77.042793,7.000000e+06,596.000000,11750.000000,30.000000
Philippines,14.599500,120.984200,1.475000e+07,1399.000000,10550.000000,7.000000
Poland,51.247300,20.018000,2.100000e+06,505.000000,4175.000000,95.500000
Portugal,38.722300,-9.139300,2.250000e+06,881.000000,2550.000000,88.000000
Puerto Rico,18.465500,-66.105700,2.217000e+06,2309.000000,950.000000,90.000000
Russia,57.845050,33.976200,7.900000e+06,1386.000000,6725.000000,28.000000
Saudi Arabia,24.130567,45.296867,2.758333e+06,850.333333,3150.000000,83.666667
Singapore,1.352100,103.819800,4.000000e+06,479.000000,8350.000000,56.000000
South Africa,-28.933900,26.430625,3.362500e+06,1146.000000,3175.000000,72.000000
South Korea,37.566500,126.978000,1.750000e+07,1049.000000,16700.000000,4.000000
Spain,40.900950,-0.765200,4.400000e+06,874.000000,5025.000000,52.000000
Sudan,15.500700,32.559900,4.000000e+06,583.000000,6850.000000,54.000000
Taiwan,24.590350,121.119500,3.850000e+06,443.000000,9550.000000,66.500000
Thailand,13.756300,100.501800,6.500000e+06,1010.000000,6450.000000,31.000000
Turkey,40.470800,30.919050,6.050000e+06,874.500000,6500.000000,45.500000
UAE,25.204800,55.270800,1.900000e+06,712.000000,2650.000000,104.000000
UK,52.491467,-1.420267,4.269000e+06,927.000000,4300.000000,66.666667
USA,38.118227,-96.781077,3.964846e+06,2888.000000,1346.153846,74.384615
Uzbekistan,41.299500,69.240100,2.200000e+06,531.000000,4150.000000,92.000000
Vietnam,10.823100,106.629700,4.900000e+06,518.000000,9450.000000,44.000000
Zimbabwe,-17.825200,31.033500,1.750000e+06,712.000000,2450.000000,112.000000

In [ ]:
# Filter numeric columns before aggregation
numeric_cols = df.select_dtypes(include='number').columns
df.groupby('Country')[numeric_cols].agg(['count', 'mean']).head()

           Latitude            Longitude           Population              \
              count       mean     count      mean      count        mean
Country
Argentina         1 -34.603700         1  -58.3816          1  11200000.0
Australia         3 -33.050733         3  149.7325          3   2724000.0
Austria           1  48.208200         1   16.3738          1   1550000.0
Azerbaijan        1  40.409300         1   49.8671          1   2100000.0
Belgium           1  50.850300         1    4.3517          1   1570000.0

           Land_area         Density              Number
               count    mean   count         mean  count        mean
Country
Argentina          1  2266.0       1  4950.000000      1   15.000000
Australia          3  1790.0       3  1516.666667      3   84.666667
Austria            1   453.0       1  3400.000000      1  118.000000
Azerbaijan         1   544.0       1  3850.000000      1   94.000000
Belgium            1   712.0       1  2200.000000      1  117.000000

In [ ]:
df.groupby('Country').agg({'City':'count','Population':'mean','Density':'max'}).head()

            City  Population  Density
Country
Argentina      1  11200000.0     4950
Australia      3   2724000.0     2100
Austria        1   1550000.0     3400
Azerbaijan     1   2100000.0     3850
Belgium        1   1570000.0     2200

### F.2 - Grouping Based On Multiple Columns

In [ ]:
teams

,division,conference,school_name,roster_url,id
0,FBS (Division I-A Teams),American Athletic,Cincinnati,http://espn.go.com/ncf/teams/roster?teamId=2132,1
1,FBS (Division I-A Teams),American Athletic,Connecticut,http://espn.go.com/ncf/teams/roster?teamId=41,2
2,FBS (Division I-A Teams),American Athletic,Houston,http://espn.go.com/ncf/teams/roster?teamId=248,3
3,FBS (Division I-A Teams),American Athletic,Louisville,http://espn.go.com/ncf/teams/roster?teamId=97,4
4,FBS (Division I-A Teams),American Athletic,Memphis,http://espn.go.com/ncf/teams/roster?teamId=235,5
...,...,...,...,...,...
247,FCS (Division I-AA Teams),SWAC,Jackson State,http://espn.go.com/ncf/teams/roster?teamId=2296,248
248,FCS (Division I-AA Teams),SWAC,Mississippi Valley State,http://espn.go.com/ncf/teams/roster?teamId=2400,249
249,FCS (Division I-AA Teams),SWAC,Prairie View A&M,http://espn.go.com/ncf/teams/roster?teamId=2504,250
250,FCS (Division I-AA Teams),SWAC,Southern University,http://espn.go.com/ncf/teams/roster?teamId=2582,251
251,FCS (Division I-AA Teams),SWAC,Texas Southern,http://espn.go.com/ncf/teams/roster?teamId=2640,252

In [ ]:
teams.groupby(['division','conference']).count()['school_name']

division                   conference
FBS (Division I-A Teams)   ACC                  14
                           American Athletic    10
                           Big 12               10
                           Big Ten              12
                           Conference USA       14
                           FBS Independents      7
                           Mid-American         13
                           Mountain West        12
                           Pac-12               12
                           SEC                  14
                           Sun Belt              8
FCS (Division I-AA Teams)  Big Sky              13
                           Big South             6
                           CAA                  11
                           FCS Independents      5
                           Ivy                   8
                           MEAC                 11
                           Missouri Valley      10
                           Northeast             7
                           Ohio Valley           9
                           Patriot League        7
                           Pioneer              12
                           SWAC                 10
                           Southern              9
                           Southland             8
Name: school_name, dtype: int64